package com.sample
 

 
 //Start turn
 rule "Start turn: init character"
 salience 200000
 	when 	
		Turn (status == TurnState.INIT)
 		character: Character ( status == Status.MOVED )
 	then 
 		character.setStatus(Status.NOT_MOVED);
 		update (character);
 end
 
  rule "Start turn: performing"
  salience 200000
 	when 	
		turn: Turn (status == TurnState.INIT)
 		not Character ( status == Status.MOVED )
 	then 
 		turn.setStatus(TurnState.PERFORMING);
 		update (turn);
 end
 
 		
 
 // Rule that handle the shrinking of the map
  rule "REMOVE PG OF THE BORDER" salience 10
    when
    	setting : Settings( time!=0 && (time % 10) == 0 && gameOver == false) and
		lom : LocatedOnMap ( ((col in (setting.getLimitColLeft() , setting.getLimitColRight())) || (row in (setting.getLimitRowUp() , setting.getLimitRowDown())))&& removable == 1 )  
    then
		retract (lom);
 end
 
   rule "EFFECTIVELY REMOVE PORTIONS OF MAP" salience 10 
    when
    	setting: Settings( time!= 0 && (time % 10) == 0 && gameOver == false) and
		not LocatedOnMap ( ((col in (setting.getLimitColLeft() , setting.getLimitColRight())) || (row in (setting.getLimitRowUp() , setting.getLimitRowDown()))) && removable == 1 )  
    then
	
		
		for (int i = setting.getLimitColLeft(); i<=setting.getLimitColRight(); i++){
			
			insert ( new Wall(i, setting.getLimitRowUp()) );
			insert ( new Wall(i, setting.getLimitRowDown()) );
			
		}
		
		for (int i = setting.getLimitRowUp() + 1; i<=setting.getLimitRowDown() -1; i++){
			
			insert ( new Wall(setting.getLimitColLeft(), i) );
			insert ( new Wall(setting.getLimitColRight(), i) );
			
		}
		
		setting.decreaseLimit();
		setting.setTime( setting.getTime() + 1);
		update ( setting );
 end
 
 
 
 rule "LOSE GAME BECAUSE YOU DIE"
 	when 
 		setting: Settings( gameOver == false ) and
 		not Hero( )
 	then 
 		setting.setGameOver(true);
 		update (setting);
 end
 
 rule "WIN GAME BECAUSE YOU ARE THE ONLY ONE"
 	when 
 		setting: Settings( gameOver == false ) and
 		Hero( ) and
 		not NPC( )
 	then 
 		setting.setGameOver(true);
 		update (setting);
 end
 
 
 rule "END TURN" 
 	when 
 		setting: Settings( ) and
 		turn : Turn ( status == TurnState.PERFORMING) and
 		not Character ( status == Status.NOT_MOVED )
 	then
 		setting.setTime(setting.getTime() + 1);
 		update (setting);
 		retract(turn);
 end
 
 