package com.sample

/*
RULES ARE INSERTED ORDERED BT DECREASING PRIORITY
*/

 
rule "NPC ATTACK RIGHT"
     salience npc.getStat(StatAbility.SPEED) * 100 + 70
    
    when
    	Settings( gameOver == false )
		npc: NPC ( status == Status.NOT_MOVED )
		character : Character ( col == npc.getCol() && row == npc.getRow()+1 )
		
    then
       System.out.print("NPC is Attacking character");
       character.increment(StatAbility.LIFE, -(npc.getStat(StatAbility.ATK)));
       npc.setStatus(Status.MOVED);
	   update ( character );       
       update ( npc );       

 end

 rule "NPC ATTACK LEFT"
     salience npc.getStat(StatAbility.SPEED) * 100 + 70
    
    when
    	Settings( gameOver == false )
		npc: NPC ( status == Status.NOT_MOVED )
		character : Character ( col == npc.getCol() && row == npc.getRow()-1 )
		
    then
       System.out.println("NPC is Attacking character");
       character.increment(StatAbility.LIFE, -(npc.getStat(StatAbility.ATK)));
       npc.setStatus(Status.MOVED);
	   update ( character );       
       update ( npc );       

 end
 
 
 rule "NPC ATTACK UP"
     salience npc.getStat(StatAbility.SPEED) * 100 + 70
    
    when
    	Settings( gameOver == false )
		npc: NPC ( status == Status.NOT_MOVED )
		character : Character ( col == npc.getCol()-1 && row == npc.getRow() )
		
    then
       System.out.print("NPC is Attacking character");
       character.increment(StatAbility.LIFE, -(npc.getStat(StatAbility.ATK)));
       npc.setStatus(Status.MOVED);
	   update ( character );       
       update ( npc );       

 end
 
  rule "NPC ATTACK DOWN"
     salience npc.getStat(StatAbility.SPEED) * 100 + 70
    
    when
    	Settings( gameOver == false )
		npc: NPC ( status == Status.NOT_MOVED )
		character : Character ( col == npc.getCol()+1 && row == npc.getRow() )
		
    then
       System.out.println("NPC is Attacking character");
       character.increment(StatAbility.LIFE, -(npc.getStat(StatAbility.ATK)));
       npc.setStatus(Status.MOVED);
	   update ( character );       
       update ( npc );       

 end
 
 
 rule "NPC CRAFT"
 salience npc.getStat(StatAbility.SPEED) * 100 + 50
    when
    	Settings( gameOver == false )
		npc: NPC ( status == Status.NOT_MOVED )
		draft: CraftObject (col == npc.getCol() && row == npc.getRow())
		
    then
       System.out.println("Npc crafting...");
       npc.increment( draft.getStatToIncrease(), draft.getBonus());
       draft.setAvaiability(draft.getAvaiability() - 1); 
       
       System.out.println("New stats: "+npc.getActualStat().toString() );
       
       npc.setStatus(Status.MOVED);
       update ( npc );
       update ( draft );       

 end
 



 
  rule "NO MOVE"
 salience npc.getStat(StatAbility.SPEED) * 100
 
    when
    	Settings( gameOver == false )
		npc : NPC( status == Status.NOT_MOVED)
		
    then
       System.out.println("npg don't move ");
       npc.setStatus(Status.MOVED);
       update(npc);

 end
 